language:
    node_js
node_js:
    node
cache:
    yarn: true
    directories:
        - "node_modules"
before_install:
    - yarn global add -g gulp-cli
install:
    - yarn install
script:
    - npm test
after_success:
    - npm run codacy-reporter
